version: '3.8'

services:
  # Development service with hot reload
  arimus-dev:
    build:
      context: .
      target: builder
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    profiles:
      - development

  # Production service
  arimus-prod:
    build:
      context: .
      target: production
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - production

  # Standalone development service (alternative)
  arimus-dev-standalone:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    profiles:
      - dev-standalone