// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmzxdrrpketoilpqytaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtenhkcnJwa2V0b2lscHF5dGFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDEzNTEsImV4cCI6MjA3MzI3NzM1MX0.RIDVsH6ajcs9M-f3hZ2kJN7KFNnw6_3lowxUjG0Qnno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});